name: color_mesh
description: A mesh (multi-point) gradient that can be used like RadialGradient and LinearGradient.
version: 0.0.4
homepage: https://github.com/hhayak/color_mesh

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  shaders:
    - shaders/mesh_gradient.frag

screenshots:
  - description: 'An example mesh gradient.'
    path: screenshots/mesh_yellow.png
  - description: 'An example mesh gradient.'
    path: screenshots/mesh.png
  - description: 'An animated mesh gradient, using AnimatedContainer and shuffling the same 4 colors.'
    path: screenshots/shuffle.gif

topics:
  - mesh
  - gradient
  - color
  - ui
  - animation

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  #web: