name: color_mesh
description: A mesh (multi-point) gradient that can be used like RadialGradient and LinearGradient.
version: 1.0.2
homepage: https://github.com/hhayak/color_mesh

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  shaders:
    - shaders/mesh_gradient.frag

screenshots:
  - description: "An example mesh gradient."
    path: screenshots/mesh.png

topics:
  - mesh
  - gradient
  - color
  - decoration
  - animation

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
